#
# Args to use in test:
#
#   Option       Type      DEF   MIN        MAX
#   -----------  --------  ---   ---        ---
#   --llMin:      CorArgLong    1     -5       - NO-LIMIT
#   --llMax:      CorArgLong    1     NO-LIMIT - 10
#   --llMinMax:   CorArgLong    1     -5       - 10
#   --ullMin:     CorArgULong   5      5       - NO-LIMIT
#   --ullMax:     CorArgULong   5     NO-LIMIT - 10
#   --ullMinMax:  CorArgULong   5      5       - 10
#
# Test Cases:
#   01. Set valid values for all six options (all on limits):
#       llMin:     -5
#       llMax:     10
#       llMinMax:  -5
#       ullMin:     5
#       ullMax:    10
#       ullMinMax:  5
#
#   02. Too high value for a signed long long (9223372036854775808) using --llMin
#   03. Too low value for a signed long long (-9223372036854775809) using --llMax
#   04. Too high value for an unsigned long long (18446744073709551616) using --ullMin
#   05. Too low value for an unsigned long long (-1) using --ullMax (CAN'T be used: -1 == 18446744073709551615)
#
#   06. Too low value for llMin (-6)
#   07. Too high value for llMax (11)
#   08. Too low value for llMinMax (-6)
#   09. Too high value for llMinMax (11)
#
#   10. Too low value for ullMin (4)
#   11. Too high value for ullMax (11)
#   12. Too low value for ullMinMax (4)
#   13. Too high value for ullMinMax (11)
#
#   14. Hexadecimal value --longVal 0x10,    see longVal == 16
#   15. Hexadecimal value --longVal H'11,    see longVal == 17
#   16. Hexadecimal value --longVal h'12,    see longVal == 18
#   17. Octadecimal value --longVal O'102,   see longVal == 19
#   18. Octadecimal value --longVal o'24,    see longVal == 20
#   19. Binary      value --longVal B'10011, see longVal == 21
#

echo "01. Set valid values for all six options (all on limits)"
echo "================================================================================"
corArgsTest --llMin -5 --llMax 10 --llMinMax -5 --ullMin 5 --ullMax 10 --ullMinMax 5
echo
echo


echo "02. Too high value for a signed long long (9223372036854775808) using --llMin"
echo "================================================================================"
corArgsTest --llMin 9223372036854775808
echo
echo


echo "03. Too low value for a signed long long (-9223372036854775809) using --llMax"
echo "================================================================================"
corArgsTest --llMax -9223372036854775809
echo
echo


echo "04. Too high value for an unsigned long long (18446744073709551616) using --ullMin"
echo "================================================================================"
corArgsTest --ullMin 18446744073709551616
echo
echo


#echo "05. Too low value for an unsigned long long (-1) using --ullMax"
#echo "================================================================================"
#corArgsTest --ullMax -1
#echo
#echo


echo "06. Too low value for llMin (-6)"
echo "================================================================================"
corArgsTest --llMin -6
echo
echo


echo "07. Too high value for llMax (11)"
echo "================================================================================"
corArgsTest --llMax 11
echo
echo


echo "08. Too low value for llMinMax (-6)"
echo "================================================================================"
corArgsTest --llMinMax -6
echo
echo


echo "09. Too high value for llMinMax (11)"
echo "================================================================================"
corArgsTest --llMinMax 11
echo
echo


echo "10. Too low value for ullMin (4)"
echo "================================================================================"
corArgsTest --ullMin 4
echo
echo


echo "11. Too high value for ullMax (11)"
echo "================================================================================"
corArgsTest --ullMax 11
echo
echo


echo "12. Too low value for ullMinMax (4)"
echo "================================================================================"
corArgsTest --ullMinMax 4
echo
echo


echo "13. Too high value for ullMinMax (11)"
echo "================================================================================"
corArgsTest --ullMinMax 11
echo
echo


echo "14. Hexadecimal value --longVal 0x10, see longVal == 16"
echo "================================================================================"
corArgsTest --longVal 0x10
echo
echo


echo "15. Hexadecimal value --longVal H'11, see longVal == 17"
echo "================================================================================"
corArgsTest --longVal "H'11"
echo
echo


echo "16. Hexadecimal value --longVal h'12, see longVal == 18"
echo "================================================================================"
corArgsTest --longVal "h'12"
echo
echo


echo "17. Octadecimal value --longVal O'23, see longVal == 19"
echo "================================================================================"
corArgsTest --longVal "O'23"
echo
echo


echo "18. Octadecimal value --longVal o'24, see longVal == 20"
echo "================================================================================"
corArgsTest --longVal "o'24"
echo
echo


echo "19. Binary value --longVal B'10101, see longVal == 21"
echo "================================================================================"
corArgsTest --longVal "B'10101"
echo
echo
